routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('index');
});

//Route::get('/panel', 'ParticipantAuthController@getLogin')->name('login');

Route::group(['prefix' => 'panel', 'namespace' => 'Admin', 'middleware' => 'admin'], function () {
    Route::resource('/users', 'UserController')->except(['show']);
    Route::resource('/codes', 'PromoCodeController')->except(['show', 'edit', 'update']);
    Route::post('/codes/xls', 'PromoCodeController@xlsPromoCode');
    Route::get('/codes/disable', 'PromoCodeController@getDisabledPromoCodes')->name('disableCodes.index');
    Route::post('/codes/generate', 'PromoCodeController@generatePromoCodes')->name('generate.codes');
    Route::resource('/partners', 'PartnerController')->except(['show']);
    Route::resource('/speakers', 'SpeakerController')->except(['show']);
    Route::get('/events', 'SpeakerController@indexEvents')->name('events.index');
    Route::get('/events/create', 'SpeakerController@createEvent')->name('events.create');
    Route::get('/events/{id}/edit', 'SpeakerController@editEvent')->name('events.edit');
    Route::resource('/participants', 'ParticipantController')->except(['show', 'create', 'store']);
});

Route::group(['middleware' => 'auth'], function () {
    Route::get('panel/logout', 'Admin\AuthController@logout');
});

Route::group(['middleware' => 'auth:participant'], function () {
    Route::get('cabinet/logout', 'ParticipantAuthController@logout');
});

Route::group(['middleware' => ['guest', 'guest:participant']], function () {
    //login for admins
    Route::get('/bzntm-panel', 'Admin\AuthController@getLogin');
    Route::post('/bzntm-panel', 'Admin\AuthController@login')->name('bzntm.login');
});

Route::group(['middleware' => ['guest:participant', 'guest']], function () {
    //login for participants
    Route::get('/login', 'ParticipantAuthController@getLogin');
    Route::post('/login', 'ParticipantAuthController@login')->name('login');
    Route::get('/join', 'ParticipantAuthController@getRegister');
    Route::post('/join', 'ParticipantAuthController@register')->name('register')->middleware('checkPromoCode');
});

Route::group(['prefix' => 'cabinet', 'namespace' => 'Cabinet', 'middleware' => 'cabinet'], function (){
    Route::get('/info', 'InfoController@index')->name('info.index');
    Route::post('/info', 'InfoController@update')->name('info.update');
    Route::post('/info/update', 'InfoController@updatePassword');
});

Route::post('/invite', 'ParticipantAuthController@invite')->name('invite');

Route::post('/become-sponsor', 'ParticipantAuthController@becomeSponsor')->name('become.sponsor');

Route::post('/contact', 'ParticipantAuthController@contactUs')->name('contact');

//Route::post('/subscribe', 'ParticipantAuthController@subscribe')->name('subscribe');//add participants to /storage/app/list.csv

Route::get('/terms-of-use', function (){
    return view('terms-of-use');//terms-of-use page
});

Route::get('/privacy-policy', function (){
    return view('privacy-policy');//privacy-policy page
});

//Route::post('/password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->middleware('guest:participant', 'checkParticipantPassword')->name('password.email');
//Route::get('/password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->middleware('guest:participant')->name('password.request');
//Route::post('/password/reset', 'Auth\ResetPasswordController@reset')->middleware('guest:participant');
//Route::get('/password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->middleware('guest:participant')->name('password.reset');

app/Participant.php
<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Log;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Support\Facades\Mail;

class Participant extends Authenticatable
{
    use Notifiable;

    protected $guarded = 'participants';

    protected $fillable = ['email', 'first_name', 'last_name', 'birthday', 'company', 'position', 'country', 'city'];

    protected $hidden = ['password', 'remember_token'];

    public function promocode()
    {
        return $this->hasOne(PromoCode::class);
    }

    public static function add($fields)
    {
        $participant = new Participant();
        $participant->fill($fields);
        $participant->save();

        return $participant;
    }

    public function edit($fields)
    {
        $this->fill($fields);
        $this->save();
    }

    public function generatePassword()
    {
        $password = str_random(10);
        $this->password = bcrypt($password);
        $this->save();

        return $password;
    }

    public function updatePassword($password)
    {
        if($password != null)
        {
            $this->password = bcrypt($password);
            $this->save();
        }
    }

    public function getPhoto()
    {
        if($this->photo == null)
        {
            return 'img/no-image.png';
        }

        return 'uploads/participants/' . $this->photo;

    }

    public function uploadPhoto($image)
    {
        if($image == null){return;}
        if($this->photo != null)
        {
            unlink(public_path('uploads/participants/' . $this->photo));
        }
        $filename = str_random(10) . '.' . $image->extension();
        $image->storeAs('uploads/participants', $filename, 'public');
        $this->photo = $filename;
        $this->save();
    }

    public function getBirthdayAttribute($value)
    {
        if($value == null){return $value;}
        $date = Carbon::createFromFormat('Y-m-d h:m:s', $value)->format('d/m/y');
        return $date;
    }

    public function setBirthdayAttribute($value)
    {
        if($value == null){return $value;}
        $date = Carbon::createFromFormat('d/m/y', $value)->format('Y-m-d h:m:s');
        return $this->attributes['birthday'] = $date;
    }

    public function getParticipantPromoCode()
    {
        if($this->promocode != null)
        {
            return $this->promocode->code;
        }

        return false;
    }

    public function getExpirationDate()
    {
        if($this->promocode != null)
        {
            $date = Carbon::parse($this->promocode->expirationDate)->format('F d Y 00:00:01');
            return $date;
        }

        return false;
    }

    public function toggleIsPay($status)
    {
        if($status == null)
        {
            $this->is_pay = 0;
            $this->save();
            return $status;
        }
        $this->is_pay = 1;
        $this->save();
        return $status;
    }

    public function setParticipantPassword($code)
    {
        $this->password = bcrypt($code);
        $this->save();

        return $code;
    }

    /*---*/
    public function sendEmailWithParticipantInfo($password, $email)
    {
        Mail::send('email.password', ['password' => $password, 'email' => $email], function ($m) {
            $m->from('top10@bzntm.com', 'TOP10 Point of Trust');
            $m->to($this->email)->subject('Your password');
        });
    }
}

app/Http/Controllers/Admin/ParticipantController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Participant;
use App\PromoCode;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Database\Eloquent\ModelNotFoundException;
use Illuminate\Support\Facades\Log;
use App\Library\Api\GetResponse;

class ParticipantController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $participants = Participant::all();
        return view('admin.participants.index', [
            'participants' => $participants,
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $participant = Participant::find($id);
        return view('admin.participants.edit', [
            'participant' => $participant,
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //dd($request->all());
        $this->validate($request, [
            'photo' => 'nullable|image|mimes:jpg,png,jpeg',
        ]);

        $promocode = PromoCode::checkPromoCode($request->get('promo_code'));
        $participant = Participant::find($id);

        if($promocode)
        {
            if($promocode->status == -1 && $participant->getParticipantPromoCode() != $promocode->code)
            {
                return redirect()->back()->with('status', 'Promotional code has expired');
            } elseif ($promocode->status == 0 && $participant->getParticipantPromoCode() != $promocode->code)
            {
                return redirect()->back()->with('status', 'Promotional code already in use');
            }


            if($participant->getParticipantPromoCode() && $participant->promocode->status != -1 && $participant->getParticipantPromoCode() != $promocode->code)
            {
                $participant->promocode->status = 1;
                $participant->promocode->participant_id = null;
                $participant->promocode->save();
                $participant->promo_code_id = $promocode->id;
                $participant->save();
            } else {
                $participant->promo_code_id = $promocode->id;
                $participant->save();
                if(!$participant->password)
                {
                    $password = $participant->setParticipantPassword($promocode->code);
                    $participant->sendEmailWithParticipantInfo($password, $participant->email);

                    /*add to "not_paid" company GetResponse*/
//                    $gr = new GetResponse('6395eda0a41ecf11c841f36989446ae3');
//
//                    $contact_data = [
//                        //'name' => $request->get('first_name') . $request->get('last_name'),
//                        'email' => $participant->email,
//                        'campaign' => [
//                            'campaignId' => 'nmFpU'//not_paid company getresponse
//                        ],
//                        'dayOfCycle' => '0',
//                    ];
//
//                    $gr->addContact($contact_data);
//
//                    $contact = $gr->getContacts([
//                        'query' => [
//                            'email' => $participant->email,
//                            'campaignId' => 'nmFpU'
//                        ]
//                    ]);
//                    $grcontact = (array)$contact;
//
//                    $participant->gr_id = $grcontact[0]->contactId;
//                    $participant->save();

                    /*nmFpU - not_paid , nmFVB - paid_for */
                }
            }

            $promocode->AssignPromoCode($participant->id);

        } elseif(!$promocode)
        {
            return redirect()->back()->with('status', 'Wrong promotional code');
        }

        $participant->edit(array_filter($request->all()));
        $toggle = $participant->toggleIsPay($request->get('is_pay'));
//        if($toggle)
//        {
//            //change company in getresponse
//            $gr = new GetResponse('6395eda0a41ecf11c841f36989446ae3');
//
//            $params = [
//                'campaign' => [
//                    'campaignId' => 'nmFVB'
//                ]
//            ];
//
//            $contact = $gr->updateContact($participant->gr_id, $params);
//            //dd($contact);
//            /*nmFpU - not_paid token, nmFVB - paid_for token*/
//        }
        $participant->uploadPhoto($request->file('photo'));

        return redirect()->route('participants.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/participants/edit.blade.php
@extends('admin.layout')

@section('content')
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                Редактирование участника
            </h1>
            @if(session('status'))
                <div style="color: #ff000e;">{!! session('status') !!}</div>
            @endif
        </section>

    <!-- Main content -->
        <section class="content">
        {{Form::open(['method' => 'put', 'route' => ['participants.update', $participant->id], 'files' => 'true'])}}
        <!-- Default box -->
            <div class="form-group" style="text-align: right">
                <label>
                    <input name="is_pay" onchange="return alert('Вы изменили статус Оплачено')" type="checkbox" class="" @if($participant->is_pay){{'checked'}}@endif>
                </label>
                <label>
                    Оплачено
                </label>
            </div>
            <div class="box">
                <div class="box-header with-border">
                    <h3 class="box-title">Редактирование участника</h3>
                </div>
                <div class="box-body">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="exampleInputName1">Имя</label>
                            <input type="text" name="first_name" value="{{$participant->first_name}}" class="form-control" id="exampleInputName1" placeholder="Имя">
                        </div>
                        <div class="form-group">
                            <label for="exampleInputLastLastName1">Фамилия</label>
                            <input name="last_name" type="text" value="{{$participant->last_name}}" class="form-control" id="exampleInputLastName1" placeholder="Фамилия">
                        </div>

                        {{--Date--}}
                        <div class="form-group">
                            <label>Дата рождения:</label>

                            <div class="input-group date">
                                <div class="input-group-addon">
                                    <i class="fa fa-calendar"></i>
                                </div>
                                <input name="birthday" type="text" class="form-control pull-right" id="datepicker" placeholder="Дата рождения" value="{{$participant->birthday}}">
                            </div>
                            <!-- /.input group -->
                        </div>

                        <div class="form-group">
                            <label for="exampleInputCompany1">Компания</label>
                            <input type="text" name="company" value="{{$participant->company}}" class="form-control" id="exampleInputCompany1" placeholder="Компания">
                        </div>

                        <div class="form-group">
                            <label for="exampleInputPosition1">Должность</label>
                            <input type="text" name="position" value="{{$participant->position}}" class="form-control" id="exampleInputPosition1" placeholder="Должность">
                        </div>

                        <div class="form-group">
                            <label for="exampleInputCountry1">Страна</label>
                            <input type="text" name="country" value="{{$participant->country}}" class="form-control" id="exampleInputCountry1" placeholder="Страна">
                        </div>

                        <div class="form-group">
                            <label for="exampleInputCity1">Город</label>
                            <input type="text" name="city" value="{{$participant->city}}" class="form-control" id="exampleInputCity1" placeholder="Город">
                        </div>

                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <img src="{{asset($participant->getPhoto())}}" alt="pic" class="img-responsive" width="200">
                            <label for="exampleInputFile">Аватар</label>
                            <input type="file" name="photo" id="exampleInputFile">

                            <p class="help-block">Какое-нибудь уведомление о форматах..</p>
                        </div>

                        <div class="form-group">
                            <label for="exampleInputName1">Email</label>
                            <input type="text" name="email" value="{{$participant->email}}" class="form-control disabled" id="exampleInputName1" disabled="disabled">
                        </div>
                        <div class="form-group">
                            <label for="exampleInputLastLastName1">Промокод</label>
                            <input name="promo_code" type="text" value="{{$participant->getParticipantPromoCode()}}" class="form-control disabled" id="exampleInputLastName1">
                        </div>

                    </div>
                </div>
                <!-- /.box-body -->
                <div class="box-footer">
                    <a href="{{route('participants.index')}}" class="btn btn-default">Назад</a>
                    <button type="submit" class="btn btn-warning pull-right">Изменить</button>
                </div>
                <!-- /.box-footer-->
            </div>
            <!-- /.box -->
            {{Form::close()}}
        </section>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->
@endsection

resources/views/admin/participants/index.blade.php
@extends('admin.layout')

@section('content')
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                Участники
            </h1>

        </section>

        <!-- Main content -->
        <section class="content">

            <!-- Default box -->
            <div class="box">
                <div class="box-header">
                    <h3 class="box-title">Участники</h3>
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    <div class="form-group">
                        {{--<a href="{{route('participants.create')}}" class="btn btn-success">Добавить</a>--}}
                    </div>
                    <table id="example1" class="table table-bordered table-striped">
                        <thead>
                        <tr>
                            <th>ID</th>
                            <th>Имя</th>
                            <th>E-mail</th>
                            <th>Аватар</th>
                            <th>Промокод</th>
                            <th>Действия</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($participants as $participant)
                            <tr>
                                <td>{{$participant->id}}</td>
                                <td>{{$participant->first_name}}</td>
                                <td>{{$participant->email}}</td>
                                <td>
                                    <img src="{{asset($participant->getPhoto())}}" alt="" class="img-responsive" width="150">
                                </td>
                                <td>{{$participant->getParticipantPromoCode()}}</td>
                                <td>
                                    <a href="{{route('participants.edit', [$participant->id])}}" class="fa fa-pencil"></a>
                                </td>
                            </tr>
                        @endforeach
                        </tfoot>
                    </table>
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->

        </section>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->
@endsection