routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('index');
});

//Route::get('/panel', 'ParticipantAuthController@getLogin')->name('login');

Route::group(['prefix' => 'panel', 'namespace' => 'Admin', 'middleware' => 'admin'], function () {
    Route::resource('/users', 'UserController')->except(['show']);
    Route::resource('/codes', 'PromoCodeController')->except(['show', 'edit', 'update']);
    Route::post('/codes/xls', 'PromoCodeController@xlsPromoCode');
    Route::get('/codes/disable', 'PromoCodeController@getDisabledPromoCodes')->name('disableCodes.index');
    Route::post('/codes/generate', 'PromoCodeController@generatePromoCodes')->name('generate.codes');
    Route::resource('/partners', 'PartnerController')->except(['show']);
    Route::resource('/speakers', 'SpeakerController')->except(['show']);
    Route::get('/events', 'SpeakerController@indexEvents')->name('events.index');
    Route::get('/events/create', 'SpeakerController@createEvent')->name('events.create');
    Route::get('/events/{id}/edit', 'SpeakerController@editEvent')->name('events.edit');
    Route::resource('/participants', 'ParticipantController')->except(['show', 'create', 'store']);
});

Route::group(['middleware' => 'auth'], function () {
    Route::get('panel/logout', 'Admin\AuthController@logout');
});

Route::group(['middleware' => 'auth:participant'], function () {
    Route::get('cabinet/logout', 'ParticipantAuthController@logout');
});

Route::group(['middleware' => ['guest', 'guest:participant']], function () {
    //login for admins
    Route::get('/bzntm-panel', 'Admin\AuthController@getLogin');
    Route::post('/bzntm-panel', 'Admin\AuthController@login')->name('bzntm.login');
});

Route::group(['middleware' => ['guest:participant', 'guest']], function () {
    //login for participants
    Route::get('/login', 'ParticipantAuthController@getLogin');
    Route::post('/login', 'ParticipantAuthController@login')->name('login');
    Route::get('/join', 'ParticipantAuthController@getRegister');
    Route::post('/join', 'ParticipantAuthController@register')->name('register')->middleware('checkPromoCode');
});

Route::group(['prefix' => 'cabinet', 'namespace' => 'Cabinet', 'middleware' => 'cabinet'], function (){
    Route::get('/info', 'InfoController@index')->name('info.index');
    Route::post('/info', 'InfoController@update')->name('info.update');
    Route::post('/info/update', 'InfoController@updatePassword');
});

Route::post('/invite', 'ParticipantAuthController@invite')->name('invite');

Route::post('/become-sponsor', 'ParticipantAuthController@becomeSponsor')->name('become.sponsor');

Route::post('/contact', 'ParticipantAuthController@contactUs')->name('contact');

//Route::post('/subscribe', 'ParticipantAuthController@subscribe')->name('subscribe');//add participants to /storage/app/list.csv

Route::get('/terms-of-use', function (){
    return view('terms-of-use');//terms-of-use page
});

Route::get('/privacy-policy', function (){
    return view('privacy-policy');//privacy-policy page
});

//Route::post('/password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->middleware('guest:participant', 'checkParticipantPassword')->name('password.email');
//Route::get('/password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->middleware('guest:participant')->name('password.request');
//Route::post('/password/reset', 'Auth\ResetPasswordController@reset')->middleware('guest:participant');
//Route::get('/password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->middleware('guest:participant')->name('password.reset');

app/PromoCode.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Log;
use Illuminate\Database\Eloquent\ModelNotFoundException;
use Carbon\Carbon;

class PromoCode extends Model
{
    protected $fillable = ['code', 'expirationDate', 'source'];

    public function participant()
    {
        return $this->hasOne(Participant::class);
    }

    public static function checkPromoCode($code)
    {
        if($code != null)
        {
            try
            {
                $promoCode = PromoCode::where('code', $code)->firstOrFail();
            } catch (ModelNotFoundException $Exception)
            {
                Log::info($Exception->getMessage());
                return false;
            }
            return $promoCode;
        }

        return null;
    }

    public function getParticipantEmail()
    {
        if($this->participant != null)
        {
            return $this->participant->email;
        }

        return 'empty';
    }

    public function getParticipantId()
    {
        if($this->participant != null)
        {
            return $this->participant->id;
        }

        return false;
    }

    public function getGetResponseId()
    {
        if($this->participant != null)
        {
            return $this->participant->gr_id;
        }

        return false;
    }

    public function disablePromoCode()
    {
        $this->status = 0;
        $this->save();
    }

    public function setActivationDate()
    {
        $this->activationDate = Carbon::now()->toDateTimeString();
        $this->save();
    }

    public function setParticipantId($id)
    {
        $this->participant_id = $id;
        $this->save();
    }

    public function getParticipantFirstName()
    {
        if($this->participant != null)
        {
            return $this->participant->first_name;
        }

        return 'empty';
    }

//    public function getExpirationDateAttribute($value)
//    {
//        //dd($value);
//        $date = Carbon::createFromFormat('Y-m-d h:m:s', $value)->format('d-m-y 00:00:01');
//        //dd($date);
//        return $date;
//    }

    public function setExpirationDateAttribute($value)
    {
        $date = Carbon::createFromFormat('d/m/y', $value)->format('Y-m-d 00:00:01');
        return $this->attributes['expirationDate'] = $date;
    }

    public static function generateRandomPromocode($length = 10) {
        $characters = '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ';
        $charactersLength = strlen($characters);
        $randomString = '';
        for ($i = 0; $i < $length; $i++) {
            $randomString .= $characters[rand(0, $charactersLength - 1)];
        }
        return $randomString;
    }

    public function AssignPromoCode($participant_id)
    {
        $this->participant_id = $participant_id;
        $this->disablePromoCode();
    }

    public function isPay()
    {
        if($this->participant != null)
        {
            if($this->participant->is_pay)
            {
                return true;
            }
            return false;
        }
        return false;
    }
}

app/Http/Controllers/Admin/PromoCodeController.php
<?php

namespace App\Http\Controllers\Admin;

use App\PromoCode;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Carbon;
use Maatwebsite\Excel\Facades\Excel;

class PromoCodeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $promocodes = PromoCode::all();
        return view('admin.promocode.index', [
            'promocodes' => $promocodes,
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.promocode.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'code' => 'required|regex:/^[A-Za-z0-9]+$/|min:5',
            'source' => 'required',
            'expirationDate' => 'required',
        ]);

        PromoCode::create($request->all());

        return redirect()->route('codes.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        PromoCode::find($id)->delete();
        return redirect()->route('codes.index');
    }

    public function generatePromoCodes(Request $request)
    {
        $this->validate($request, [
            'count' => 'required',
            'expirationDate' => 'required',
            'source' => 'required',
        ]);

        for ($i = 1; $i <= $request->get('count'); $i++)
        {
            $code = PromoCode::generateRandomPromocode(6);
            PromoCode::create([
                'code' => $code,
                'expirationDate' => $request->get('expirationDate'),
                'source' => $request->get('source'),
            ]);
        }

        return redirect()->route('codes.index')->with('status', 'Промокоды сгенерированы');
    }

    public function getDisabledPromoCodes()
    {
        $promocodes = PromoCode::where('status', '-1')->get();
        return view('admin.promocode.disable', [
            'promocodes' => $promocodes,
        ]);
    }

    public function xlsPromoCode()
    {
        $promocodes = PromoCode::all();
//        dd($promocodes);
        Excel::create('promo', function ($excel) use ($promocodes) {
            $excel->sheet('promo', function ($sheet) use ($promocodes) {
                $sheet->cell('A1', 'Source');
                for($i = 2; $i <= count($promocodes) + 1; $i++)
                {
                    $sheet->cell('A'.$i, $promocodes[$i - 2]->source);//
                }

                $sheet->cell('B1', 'Code');
                for($i = 2; $i <= count($promocodes) + 1; $i++)
                {
                    $sheet->cell('B'.$i, $promocodes[$i - 2]->code);//
                }

                $sheet->cell('C1', 'Email');
                for($i = 2; $i <= count($promocodes) + 1; $i++)
                {
                    $sheet->cell('C'.$i, $promocodes[$i - 2]->getParticipantEmail());//
                }

                $sheet->cell('D1', 'Name');
                for($i = 2; $i <= count($promocodes) + 1; $i++)
                {
                    $sheet->cell('D'.$i, $promocodes[$i - 2]->getParticipantFirstName());//
                }

                $sheet->cell('E1', 'ExpirationDate');
                for($i = 2; $i <= count($promocodes) + 1; $i++)
                {
                    $sheet->cell('E'.$i, $promocodes[$i - 2]->expirationDate);//
                }
            });
        })->download('xlsx');
    }
//    public function show()
//    {
//        return abort(404);
//    }
}

resources/views/admin/promocode/create.blade.php
@extends('admin.layout')

@section('content')
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                Добавить промокод
            </h1>
        </section>

        <!-- Main content -->
        <section class="content">
            {{Form::open(['method' => 'post', 'route' => 'codes.store'])}}
                <!-- Default box -->
                <div class="box">
                    <div class="box-header with-border">
                        <h3 class="box-title">Добавляем промокод</h3>
                        @include('admin.error')
                    </div>
                    <div class="box-body">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="exampleInputPromo1">Промокод</label>
                                <input type="text" name="code" class="form-control" id="exampleInputPromo1" placeholder="Промокод">
                            </div>
                            <!-- Date -->
                            <div class="form-group">
                                <label>Действителен до:</label>

                                <div class="input-group date">
                                    <div class="input-group-addon">
                                        <i class="fa fa-calendar"></i>
                                    </div>
                                    <input type="text" name="expirationDate" class="form-control pull-right" id="datepicker">
                                </div>
                                <!-- /.input group -->
                            </div>

                            <div class="form-group">
                                <label>Source:</label>
                                <select name="source" class="form-control select2" data-placeholder="Выберите" style="width: 100%;">
                                    <option value="Conference">Conference</option>
                                    <option value="Referrals">Referrals</option>
                                    <option value="Free">Free</option>
                                    <option value="Media">Media</option>
                                    <option value="Waitlist">Waitlist</option>
                                    <option value="Influencers">Influencers</option>
                                </select>
                            </div>
                        </div>
                    </div>
                    <!-- /.box-body -->
                    <div class="box-footer">
                        <a href="{{route('codes.index')}}" class="btn btn-default">Назад</a>
                        <button type="submit" class="btn btn-success pull-right">Добавить</button>
                    </div>
                    <!-- /.box-footer-->
                </div>
                <!-- /.box -->
            {{Form::close()}}
        </section>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->
@endsection

resources/views/admin/promocode/disable.blade.php
@extends('admin.layout')

@section('content')
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                Деактивированные промокоды
            </h1>
        </section>

        <!-- Main content -->
        <section class="content">

            <!-- Default box -->
            <div class="box">
                <div class="box-header">
                    <h3 class="box-title">Деактивированные промокоды</h3>
                    @include('admin.error')
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    <table id="example1" class="table table-bordered table-striped">
                        <thead>
                        <tr>
                            <th>ID</th>
                            <th>Source</th>
                            <th>Промокод</th>
                            <th>Email</th>
                            <th>Статус</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($promocodes as $promocode)
                            <tr>
                                <td>{{$promocode->id}}</td>
                                <td>{{$promocode->source}}</td>
                                <td>{{$promocode->code}}</td>
                                <td>{{$promocode->getParticipantEmail()}}</td>
                                <td>
                                    @if($promocode->status == 1)
                                        {{--<i class="fa fa-thumbs-o-up"></i>--}}
                                        Активен
                                    @elseif($promocode->status == -1)
                                        {{--<i class="fa fa-lock"></i>--}}
                                        Отключен
                                    @else
                                        Зарезервирован
                                    @endif
                                </td>
                            </tr>
                        @endforeach
                        </tfoot>
                    </table>
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->

        </section>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->
@endsection

resources/views/admin/promocode/index.blade.php
@extends('admin.layout')

@section('content')
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header" style="display: flex;justify-content: space-between;">
            <h1>
                Промокод
            </h1>
            {{Form::open(['method' => 'post', 'url' => 'panel/codes/xls'])}}
            <button type="submit" class="btn btn-success pull-right">Выгрузить промокоды</button>
            {{Form::close()}}
        </section>

        <!-- Main content -->
        <section class="content">

            <!-- Default box -->
            <div class="box">
                <div class="box-header">
                    <h3 class="box-title">Промокод</h3>
                    @include('admin.error')
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    <div class="form-group" style="display: flex;justify-content: space-between;align-items: center;">
                        <a href="{{route('codes.create')}}" class="btn btn-success">Добавить один</a>
                        {{Form::open(['method' => 'post', 'route' => 'generate.codes', 'style' => 'display:flex;align-items:center;', 'id' => 'generate'])}}
                            <div class="form-group">
                                <label>Действителен до:</label>

                                <div class="input-group date">
                                    <div class="input-group-addon">
                                        <i class="fa fa-calendar"></i>
                                    </div>
                                    <input name="expirationDate" type="text" class="form-control pull-right" id="datepicker" placeholder="Действителен до">
                                </div>
                                <!-- /.input group -->
                            </div>
                            <div class="form-group">
                                <label>Source:</label>
                                <select name="source" class="form-control select2" id="source" data-placeholder="Выберите" style="width: 100%;">
                                    <option value="Conference">Conference</option>
                                    <option value="Referrals">Referrals</option>
                                    <option value="Free">Free</option>
                                    <option value="Media">Media</option>
                                    <option value="Waitlist">Waitlist</option>
                                    <option value="Influencers">Influencers</option>
                                </select>
                            </div>
                            <div class="form-group">
                                <label for="exampleInputPromo1">Промокод</label>
                                <input type="text" name="count" class="form-control" id="exampleInputPromo1" placeholder="Количество" value="{{old('count')}}">
                            </div>
                            <button type="submit" class="btn btn-success pull-right">Генерировать</button>
                        {{Form::close()}}
                    </div>
                    <table id="example1" class="table table-bordered table-striped">
                        <thead>
                        <tr>
                            <th>ID</th>
                            <th>Source</th>
                            <th>Промокод</th>
                            <th>Email</th>
                            <th>Действителен до</th>
                            <th>Статус</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($promocodes as $promocode)
                            <tr>
                                <td>{{$promocode->id}}</td>
                                <td>{{$promocode->source}}</td>
                                <td>{{$promocode->code}}</td>
                                <td>
                                    @if($promocode->participant)
                                        <a href="{{route('participants.edit', $promocode->getParticipantId())}}">
                                            {{$promocode->getParticipantEmail()}}
                                        </a>
                                    @else
                                        {{$promocode->getParticipantEmail()}}
                                    @endif
                                </td>
                                <td>{{$promocode->expirationDate}}</td>
                                <td>
                                    @if($promocode->status == 1)
                                        {{--<i class="fa fa-thumbs-o-up"></i>--}}
                                        Активен
                                    @elseif($promocode->status == -1)
                                        {{--<i class="fa fa-lock"></i>--}}
                                        Отключен
                                    @elseif($promocode->isPay())
                                        Оплачен
                                    @else
                                        Зарезервирован
                                    @endif
                                    {{Form::open(['method' => 'delete', 'route' => ['codes.destroy', $promocode->id]])}}
                                    <button type="submit" class="delete" onclick="return confirm('Вы уверены, что хотите удалить промокод?')">
                                        <i class="fa fa-remove"></i>
                                    </button>
                                    {{Form::close()}}
                                </td>
                            </tr>
                        @endforeach
                        </tfoot>
                    </table>
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->

        </section>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->
@endsection