routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('index');
});

//Route::get('/panel', 'ParticipantAuthController@getLogin')->name('login');

Route::group(['prefix' => 'panel', 'namespace' => 'Admin', 'middleware' => 'admin'], function () {
    Route::resource('/users', 'UserController')->except(['show']);
    Route::resource('/codes', 'PromoCodeController')->except(['show', 'edit', 'update']);
    Route::post('/codes/xls', 'PromoCodeController@xlsPromoCode');
    Route::get('/codes/disable', 'PromoCodeController@getDisabledPromoCodes')->name('disableCodes.index');
    Route::post('/codes/generate', 'PromoCodeController@generatePromoCodes')->name('generate.codes');
    Route::resource('/partners', 'PartnerController')->except(['show']);
    Route::resource('/speakers', 'SpeakerController')->except(['show']);
    Route::get('/events', 'SpeakerController@indexEvents')->name('events.index');
    Route::get('/events/create', 'SpeakerController@createEvent')->name('events.create');
    Route::get('/events/{id}/edit', 'SpeakerController@editEvent')->name('events.edit');
    Route::resource('/participants', 'ParticipantController')->except(['show', 'create', 'store']);
});

Route::group(['middleware' => 'auth'], function () {
    Route::get('panel/logout', 'Admin\AuthController@logout');
});

Route::group(['middleware' => 'auth:participant'], function () {
    Route::get('cabinet/logout', 'ParticipantAuthController@logout');
});

Route::group(['middleware' => ['guest', 'guest:participant']], function () {
    //login for admins
    Route::get('/bzntm-panel', 'Admin\AuthController@getLogin');
    Route::post('/bzntm-panel', 'Admin\AuthController@login')->name('bzntm.login');
});

Route::group(['middleware' => ['guest:participant', 'guest']], function () {
    //login for participants
    Route::get('/login', 'ParticipantAuthController@getLogin');
    Route::post('/login', 'ParticipantAuthController@login')->name('login');
    Route::get('/join', 'ParticipantAuthController@getRegister');
    Route::post('/join', 'ParticipantAuthController@register')->name('register')->middleware('checkPromoCode');
});

Route::group(['prefix' => 'cabinet', 'namespace' => 'Cabinet', 'middleware' => 'cabinet'], function (){
    Route::get('/info', 'InfoController@index')->name('info.index');
    Route::post('/info', 'InfoController@update')->name('info.update');
    Route::post('/info/update', 'InfoController@updatePassword');
});

Route::post('/invite', 'ParticipantAuthController@invite')->name('invite');

Route::post('/become-sponsor', 'ParticipantAuthController@becomeSponsor')->name('become.sponsor');

Route::post('/contact', 'ParticipantAuthController@contactUs')->name('contact');

//Route::post('/subscribe', 'ParticipantAuthController@subscribe')->name('subscribe');//add participants to /storage/app/list.csv

Route::get('/terms-of-use', function (){
    return view('terms-of-use');//terms-of-use page
});

Route::get('/privacy-policy', function (){
    return view('privacy-policy');//privacy-policy page
});

//Route::post('/password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->middleware('guest:participant', 'checkParticipantPassword')->name('password.email');
//Route::get('/password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->middleware('guest:participant')->name('password.request');
//Route::post('/password/reset', 'Auth\ResetPasswordController@reset')->middleware('guest:participant');
//Route::get('/password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->middleware('guest:participant')->name('password.reset');

resources/views/admin/events/create.blade.php
@extends('admin.layout')

@section('content')
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                Добавить событие
            </h1>
        </section>

        <!-- Main content -->
        <section class="content">
        {{Form::open(['method' => 'post', 'route' => 'speakers.store', 'files' => 'true'])}}
        <!-- Default box -->
            <div class="box">
                <div class="box-header with-border">
                    <h3 class="box-title">Добавляем спикера</h3>
                    @include('admin.error')
                </div>
                <div class="box-body">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="exampleInputName1">Название</label>
                            <input type="text" name="title" value="{{old('title')}}" class="form-control" id="exampleInputName1" placeholder="Название">
                        </div>
                        {{--<div class="form-group">
                            <label for="exampleInputDescription1">Биография</label>
                            <textarea name="description" id="" cols="30" rows="7" class="form-control" id="exampleInputDescription1" placeholder="Биография">{{old('description')}}</textarea>
                        </div>--}}
                    </div>
                    <div class="col-md-6">
                        <div class="col-md-12">
                            <div class="form-group col-md-6">
                                <label>Начало:</label>

                                <div class="input-group date datetimepicker2">
                                    <div class="input-group-addon">
                                        <i class="fa fa-calendar"></i>
                                    </div>
                                    <input type="text" name="time_start" class="form-control pull-right">
                                </div>
                                <!-- /.input group -->
                            </div>
                            <div class="form-group col-md-6">
                                <label>Окончание:</label>

                                <div class="input-group date datetimepicker2">
                                    <div class="input-group-addon">
                                        <i class="fa fa-calendar"></i>
                                    </div>
                                    <input type="text" name="time_end" class="form-control pull-right">
                                </div>
                                <!-- /.input group -->
                            </div>
                        </div>
                    </div>
                </div>
                {{--hide input--}}
                <input type="hidden" name="is_speaker" value="0">
                <!-- /.box-body -->
                <div class="box-footer">
                    <a href="{{route('speakers.index')}}" class="btn btn-default">Назад</a>
                    <button type="submit" class="btn btn-success pull-right">Добавить</button>
                </div>
                <!-- /.box-footer-->
            </div>
            <!-- /.box -->
            {{Form::close()}}
        </section>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->
@endsection

resources/views/admin/events/edit.blade.php
@extends('admin.layout')

@section('content')
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                Редактирование спикера
            </h1>
        </section>

        <!-- Main content -->
        <section class="content">
        {{Form::open(['method' => 'put', 'route' => ['speakers.update', $speaker->id], 'files' => 'true'])}}
        <!-- Default box -->
            <div class="box">
                <div class="box-header with-border">
                    <h3 class="box-title">Редактирование события</h3>
                </div>
                <div class="box-body">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="exampleInputName1">Название</label>
                            <input type="text" name="title" value="{{$speaker->title}}" class="form-control" id="exampleInputName1" placeholder="Название">
                        </div>
                        {{--<div class="form-group">
                            <label for="exampleInputDescription1">Описание</label>
                            <textarea name="description" id="" cols="30" rows="7" class="form-control" id="exampleInputDescription1" placeholder="Биография">{{$speaker->description}}</textarea>
                        </div>--}}
                    </div>
                    <div class="col-md-6">
                        <div class="col-md-12">
                            <div class="form-group col-md-6">
                                <label>Начало:</label>

                                <div class="input-group date datetimepicker2">
                                    <div class="input-group-addon">
                                        <i class="fa fa-calendar"></i>
                                    </div>
                                    <input type="text" name="time_start" class="form-control pull-right" value="{{$speaker->time_start}}">
                                </div>
                                <!-- /.input group -->
                            </div>
                            <div class="form-group col-md-6">
                                <label>Окончание:</label>

                                <div class="input-group date datetimepicker2">
                                    <div class="input-group-addon">
                                        <i class="fa fa-calendar"></i>
                                    </div>
                                    <input type="text" name="time_end" class="form-control pull-right" value="{{$speaker->time_end}}">
                                </div>
                                <!-- /.input group -->
                            </div>
                        </div>
                    </div>
                </div>
                {{--hide input is_speaker--}}
                <input type="hidden" name="is_speaker" value="0">
                <!-- /.box-body -->
                <div class="box-footer">
                    <a href="{{route('speakers.index')}}" class="btn btn-default">Назад</a>
                    <button type="submit" class="btn btn-warning pull-right">Изменить</button>
                </div>
                <!-- /.box-footer-->
            </div>
            <!-- /.box -->
            {{Form::close()}}
        </section>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->
@endsection

resources/views/admin/events/index.blade.php
@extends('admin.layout')

@section('content')
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                Спикеры
            </h1>

        </section>

        <!-- Main content -->
        <section class="content">

            <!-- Default box -->
            <div class="box">
                <div class="box-header">
                    <h3 class="box-title">Спикеры</h3>
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    <div class="form-group">
                        <a href="{{route('events.create')}}" class="btn btn-success">Добавить</a>
                    </div>
                    <table id="example1" class="table table-bordered table-striped">
                        <thead>
                        <tr>
                            <th>ID</th>
                            <th>Название события</th>
                            <th>Время</th>
                            <th>Действия</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($speakers as $speaker)
                            <tr>
                                <td>{{$speaker->id}}</td>
                                <td>{{$speaker->title}}</td>
                                <td>{{$speaker->time_start}} - {{$speaker->time_end}}</td>
                                <td>
                                    <a href="{{route('events.edit', $speaker->id)}}" class="fa fa-pencil"></a>
                                    {{Form::open(['method' => 'delete', 'route' => ['speakers.destroy', $speaker->id]])}}
                                    <button type="submit" class="delete" onclick="return confirm('Вы уверены, что хотите удалить событие?')">
                                        <i class="fa fa-remove"></i>
                                    </button>
                                    {{Form::close()}}
                                </td>
                            </tr>
                        @endforeach
                        </tfoot>
                    </table>
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->

        </section>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->
@endsection